# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32, verbose_name='token值')),
                ('time', models.IntegerField(verbose_name='token过期时间')),
                ('create_time', models.DateTimeField(verbose_name='token创建时间')),
                ('user_id', models.SmallIntegerField(verbose_name='用户id')),
            ],
        ),
    ]
