# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('mac', models.CharField(max_length=32, verbose_name='mac地址')),
                ('ip', models.CharField(max_length=32, verbose_name='Ip地址')),
                ('sys_type', models.CharField(max_length=32, verbose_name='系统类型')),
                ('cpu_count', models.IntegerField(verbose_name='CPU个数')),
                ('disk', models.CharField(max_length=32, verbose_name='硬盘')),
                ('memory', models.CharField(max_length=32, verbose_name='内存')),
            ],
            options={
                'verbose_name': '设备表',
                'verbose_name_plural': '设备表',
            },
        ),
    ]
