# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-23 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
    ]
